### ISSUE TITLE
Null error

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/dDiscordBot#11]
Hi, I got this error when trying to use my bot :

```
[17:04:32] [Thread-35/INFO]: [org.eclipse.jetty.util.log] Logging initialized @32974ms to org.eclipse.jetty.util.log.Slf4jLog
[17:04:32] [Thread-35/INFO]: [sx.blah.discord.Discord4J] Discord4J v2.10.1 be2318c (https://github.com/austinv11/Discord4J)
[17:04:32] [Thread-35/INFO]: [sx.blah.discord.Discord4J] A Java binding for the official Discord API, forked from the inactive 
;https://github.co https://github.com/nerd/Discord4J. Copyright (c) 2017, Licensed under GNU LGPLv3
```

```
18:09:32] [RequestBuffer Initial Executor/WARN]: [sx.blah.discord.Discord4J] RequestBuffer handled an uncaught exception!
java.lang.NullPointerException: null
at com.denizenscript.ddiscordbot.DiscordCommand.lambda$execute$1(DiscordCommand.java:244) ~[?:?]
at sx.blah.discord.util.RequestBuffer.lambda$request$1(RequestBuffer.java:84) ~[?:?]
at sx.blah.discord.util.RequestBuffer$RequestFuture$RequestCallable.call(RequestBuffer.java:286) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
at sx.blah.discord.util.RequestBuffer$RequestFuture.run(RequestBuffer.java:259) ~[?:?]
at sx.blah.discord.util.RequestBuffer$RequestFuture.access$200(RequestBuffer.java:162) ~[?:?]
at sx.blah.discord.util.RequestBuffer.lambda$request$0(RequestBuffer.java:50) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181
```

**Version** : git-Paper-597 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
**Denizen version** : 1.0.3-SNAPSHOT (build 1670-REL)
**dDiscordBot version** :  0.5-b18

I use BungeeCoord, maybe it is related ?

**Comment by mcmonkey4eva** [comment]
That looks like you just fed a bad channel ID.

**Comment by Astrareach** [comment]
I have made sure to use the new version (19) and verify multiple time the channel id and proprer token etc. I got the same problem :

Full server log : https://pastebin.com/VxfUcMaJ




The problem is that the bot never get online (I have made sure that everything work on the bot side)

When I connect, (use the command discord id:discord_chat_relay connect code:MY_BOT_TOKEN
I should see a confirmation message right after that I am connected to 1 thing. I don't have this message : https://pastebin.com/j8ckwQYV

**Comment by mcmonkey4eva** [comment]
Use build 20, which patches the exception.

Connection failure is most likely a network problem of some form on your end. You appear to be running in a hyperstrict limited JVM environment (based on the `JVM-Block` output). Try running on an actual server.
