### ISSUE TITLE
Command not send

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/dDiscordBot#3]
```
[12:12:18 INFO]: MrMaleficus lost connection: Disconnected
[12:12:48 WARN]: 12:12:48.887
[12:12:48 WARN]: : [
[12:12:48 WARN]: ERROR
[12:12:48 WARN]: ][
[12:12:48 WARN]: Server thread
[12:12:48 WARN]: ][
[12:12:48 WARN]: sx.blah.discord.Discord4J
[12:12:48 WARN]: ] - 
[12:12:48 WARN]: Discord4J Internal Exception
[12:12:48 WARN]: java.net.SocketException: Operation timed out (Read failed)
[12:12:48 WARN]: 	at java.net.SocketInputStream.socketRead0(Native Method)
[12:12:48 WARN]: 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
[12:12:48 WARN]: 	at java.net.SocketInputStream.read(SocketInputStream.java:171)
[12:12:48 WARN]: 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
[12:12:48 WARN]: 	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
[12:12:48 WARN]: 	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
[12:12:48 WARN]: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
[12:12:48 WARN]: 	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
[12:12:48 WARN]: 	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
[12:12:48 WARN]: 	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
[12:12:48 WARN]: 	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
[12:12:48 WARN]: 	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
[12:12:48 WARN]: 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
[12:12:48 WARN]: 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
[12:12:48 WARN]: 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
[12:12:48 WARN]: 	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
[12:12:48 WARN]: 	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
[12:12:48 WARN]: 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
[12:12:48 WARN]: 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
[12:12:48 WARN]: 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
[12:12:48 WARN]: 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
[12:12:48 WARN]: 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
[12:12:48 WARN]: 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
[12:12:48 WARN]: 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
[12:12:48 WARN]: 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
[12:12:48 WARN]: 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
[12:12:48 WARN]: 	at sx.blah.discord.api.internal.Requests$Request.request(Requests.java:297)
[12:12:48 WARN]: 	at sx.blah.discord.api.internal.Requests$Request.request(Requests.java:263)
[12:12:48 WARN]: 	at sx.blah.discord.api.internal.Requests$Request.makeRequest(Requests.java:252)
[12:12:48 WARN]: 	at sx.blah.discord.api.internal.Requests$Request.makeRequest(Requests.java:210)
[12:12:48 WARN]: 	at sx.blah.discord.api.internal.Requests$Request.makeRequest(Requests.java:161)
[12:12:48 WARN]: 	at sx.blah.discord.handle.impl.obj.Channel.sendMessage(Channel.java:460)
[12:12:48 WARN]: 	at sx.blah.discord.handle.impl.obj.Channel.sendMessage(Channel.java:441)
[12:12:48 WARN]: 	at sx.blah.discord.handle.impl.obj.Channel.sendMessage(Channel.java:431)
[12:12:48 WARN]: 	at com.denizenscript.ddiscordbot.DiscordCommand.execute(DiscordCommand.java:172)
[12:12:48 WARN]: 	at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:252)
[12:12:48 WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54)
[12:12:48 WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:678)
[12:12:48 WARN]: 	at net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:61)
[12:12:48 WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue$1.run(ScriptQueue.java:509)
[12:12:48 WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:528)
[12:12:48 WARN]: 	at net.aufdemrand.denizencore.events.ScriptEvent.run(ScriptEvent.java:276)
[12:12:48 WARN]: 	at net.aufdemrand.denizencore.events.ScriptEvent.fire(ScriptEvent.java:240)
[12:12:48 WARN]: 	at net.aufdemrand.denizen.events.player.PlayerQuitsScriptEvent.onPlayerQuits(PlayerQuitsScriptEvent.java:101)
[12:12:48 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:12:48 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:12:48 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:12:48 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:12:48 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[12:12:48 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:12:48 WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[12:12:48 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[12:12:48 WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:405)
[12:12:48 WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1102)
[12:12:48 WARN]: 	at net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_12_R1.a(AbstractListenerPlayIn_v1_12_R1.java:231)
[12:12:48 WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:321)
[12:12:48 WARN]: 	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:174)
[12:12:48 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845)
[12:12:48 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[12:12:48 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[12:12:48 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[12:12:48 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[12:12:48 INFO]:  ERROR! Woah!! An exception has been called with this command! 
[12:12:48 INFO]:  ERROR! Internal exception was thrown! 
[12:12:48 WARN]: sx.blah.discord.util.DiscordException: Message was unable to be sent (Discord didn't return a response).
[12:12:48 WARN]: 	at sx.blah.discord.handle.impl.obj.Channel.sendMessage(Channel.java:469)
[12:12:48 WARN]: 	at sx.blah.discord.handle.impl.obj.Channel.sendMessage(Channel.java:441)
[12:12:48 WARN]: 	at sx.blah.discord.handle.impl.obj.Channel.sendMessage(Channel.java:431)
[12:12:48 WARN]: 	at com.denizenscript.ddiscordbot.DiscordCommand.execute(DiscordCommand.java:172)
[12:12:48 WARN]: 	at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:252)
[12:12:48 WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54)
[12:12:48 WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:678)
[12:12:48 WARN]: 	at net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:61)
[12:12:48 WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue$1.run(ScriptQueue.java:509)
[12:12:48 WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:528)
[12:12:48 WARN]: 	at net.aufdemrand.denizencore.events.ScriptEvent.run(ScriptEvent.java:276)
[12:12:48 WARN]: 	at net.aufdemrand.denizencore.events.ScriptEvent.fire(ScriptEvent.java:240)
[12:12:48 WARN]: 	at net.aufdemrand.denizen.events.player.PlayerQuitsScriptEvent.onPlayerQuits(PlayerQuitsScriptEvent.java:101)
[12:12:48 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:12:48 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:12:48 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:12:48 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:12:48 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[12:12:48 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:12:48 WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[12:12:48 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[12:12:48 WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:405)
[12:12:48 WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1102)
[12:12:48 WARN]: 	at net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_12_R1.a(AbstractListenerPlayIn_v1_12_R1.java:231)
[12:12:48 WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:321)
[12:12:48 WARN]: 	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:174)
[12:12:48 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845)
[12:12:48 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[12:12:48 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[12:12:48 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[12:12:48 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[12:12:48 INFO]: +> [Denizen] (Attempted: DISCORD "id:BraveBot" "message" "channel:414562013222797312" "<&co>full_moon_with_face<&co> **<pl.name> s'est dÃ©connectÃ©.** (En ligne <&co> 
                   <server.list_online_players.size.sub[1]>/<server.max_players>)")
```

**Comment by mcmonkey4eva** [comment]
Your server or Discord's servers lagged, and thus failed to send a message.
