### ISSUE TITLE
discord_embed not working anymore.

### ISSUE THREAD

**Issue by BijuuKrunos** [DenizenScript/dDiscordBot#41]
dDiscordBot is generating me an exception if i want to use the <discord_embed> in the message section:

Script:

weekend_cave_spider:
    type: task
    script:
    - ~discordconnect id:590086849696104455 token:<secret[discord_token]>
    - ~discordmessage id:590086849696104455 channel:<discord[590086849696104455].group[HeroBlade].channel[happy-weekend]> "<discord_embed[title=Höhlenspinne;description=~~28~~ 🠖 140]>"

debug console output:

`> ex run weekend_cave_spider
[08:49:30 INFO]: Starting InstantQueue 'EXCOMMAND_704_GradesVoxlltv'...
[08:49:30 INFO]: +- Queue 'EXCOMMAND_704_GradesVoxlltv' Executing: (line 1) RUN weekend_cave_spider ---------+
[08:49:30 INFO]: +> Executing 'RUN': script='s@weekend_cave_spider (TASK)'
[08:49:30 INFO]: Completing queue 'EXCOMMAND_704_GradesVoxlltv' in 1ms.
[08:49:30 INFO]: +> [JDA] [Thread-84] INFO JDA - Login Successful!
[08:49:31 INFO]: +> [JDA] [JDA MainWS-ReadThread] INFO WebSocketClient - Connected to WebSocket
[08:49:31 INFO]: +> [JDA] [JDA MainWS-ReadThread] INFO JDA - Finished Loading!
[08:49:31 WARN]: [dDiscordBot] Plugin dDiscordBot v0.7 (build 230) generated an exception while executing task 4730
java.lang.NoSuchMethodError: 'com.denizenscript.denizencore.objects.core.ElementTag com.denizenscript.denizencore.objects.core.MapTag.getElement(java.lang.String)'
        at com.denizenscript.ddiscordbot.objects.DiscordEmbedTag.build(DiscordEmbedTag.java:129) ~[dDiscordBot-0.7-b230.jar:?]
        at com.denizenscript.ddiscordbot.commands.DiscordMessageCommand.lambda$execute$0(DiscordMessageCommand.java:233) ~[dDiscordBot-0.7-b230.jar:?]
        at com.denizenscript.ddiscordbot.commands.DiscordMessageCommand.lambda$execute$1(DiscordMessageCommand.java:284) ~[dDiscordBot-0.7-b230.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-386]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-386]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

tested with new and old <discord_embed> Format.

If I just use a normal message everything is fine.

**Comment by mcmonkey4eva** [comment]
support is on discord @ https://discord.gg/Q6pZGSR
